# Problem Set 2

## For this assignment, submit Python code to create, fit, and evaluate your final, best model for predicting fuel efficiency. 

The code you submit should at the minimum have these peices:
* load the data
* select (and create, if needed) the predictor variables for the model
* create and fit the linear model
* print model evaluation information, which must include, at a minimum R2

In [9]:
# Step 1: load the data 
import pandas as pd
df = pd.read_csv('Data/auto_mpg.csv') # note I am reading this data in from my data folder in the GitHub Repository
#df = pd.read_csv('/blue/zoo6927/share/Jupyter_Content/data/auto_mpg.csv') # Use this script if running on HyperGator Server
df # print data frame to make sure it looks okay

,mpg,cyl,disp,hp,weight,accel,year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [35]:
# Step 2: Select the predictor variables for the model 

x = df[['cyl','disp','weight','accel','year']] #selected 5 variables
y = df[['mpg']]

print(x)
print(y)

     cyl   disp  weight  accel  year
0      8  307.0    3504   12.0    70
1      8  350.0    3693   11.5    70
2      8  318.0    3436   11.0    70
3      8  304.0    3433   12.0    70
4      8  302.0    3449   10.5    70
..   ...    ...     ...    ...   ...
393    4  140.0    2790   15.6    82
394    4   97.0    2130   24.6    82
395    4  135.0    2295   11.6    82
396    4  120.0    2625   18.6    82
397    4  119.0    2720   19.4    82

[398 rows x 5 columns]
      mpg
0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
..    ...
393  27.0
394  44.0
395  32.0
396  28.0
397  31.0

[398 rows x 1 columns]

In [34]:
# Step 3 Create and fit the linear model
from sklearn.linear_model import LinearRegression

model = LinearRegression().fit(x,y)

print(model.intercept_, model.coef_) # print model coef

[-14.56969048] [[-0.25858516  0.00726771 -0.00692571  0.08034746  0.75530084]]

In [36]:
# Step 4 print model evaluation information: R2 & MSE
import numpy as np

# First write function to return MSE
def mse(model, x, y):
    return np.mean((y - model.predict(x))**2)


print("MSE is", mse(model, x, y))
print("R2 is", model.score(x,y))

MSE is mpg    11.657832
dtype: float64
R2 is 0.8086876515237436